default:
  image: node:22-alpine

deploy-pages:
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn build
  pages:
    publish: dist
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
