default:
  image: node:22-alpine

pages:
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist
  publish: dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
